project_id = "ayjdtstugbqoadgipzon"

[functions.ai-chat]
verify_jwt = false

[functions.product-analyzer]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.export-to-odoo]
verify_jwt = true

[functions.search-product-images]
verify_jwt = true

[functions.sync-odoo-categories]
verify_jwt = true
