project_id = "ayjdtstugbqoadgipzon"

[functions.ai-chat]
verify_jwt = false

[functions.send-email-campaign]
verify_jwt = true

[functions.manage-newsletter]
verify_jwt = false

[functions.product-analyzer]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.export-to-odoo]
verify_jwt = true

[functions.search-product-images]
verify_jwt = true

[functions.sync-odoo-categories]
verify_jwt = true

[functions.advanced-product-analyzer]
verify_jwt = true

[functions.market-intelligence]
verify_jwt = true

[functions.export-to-shopify]
verify_jwt = true

[functions.sync-shopify-categories]
verify_jwt = true

[functions.export-to-woocommerce]
verify_jwt = true

[functions.export-to-prestashop]
verify_jwt = true

[functions.export-to-magento]
verify_jwt = true

[functions.export-to-salesforce]
verify_jwt = true

[functions.export-to-sap]
verify_jwt = true

[functions.export-to-uber_eats]
verify_jwt = true

[functions.export-to-deliveroo]
verify_jwt = true

[functions.export-to-just_eat]
verify_jwt = true

[functions.export-to-windev]
verify_jwt = true
